name: CI/CD Pipeline - Fitness Diet App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (latest + sha)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            harihk27/fitness-diet-app:latest
            harihk27/fitness-diet-app:${{ github.sha }}
